### PR TITLE
Fix: Draggable view stuck on screen after release

### PR DESCRIPTION
**Pull request by Georgio-Saad**

### CODE REVIEW

**Comment by LunatiqueCoder** [comment]
@lafiosca I managed to fix the issue by forking and migrating to `react-native-reanimated`, where the `finished` functionality works as expected. There's still a little bit of tinkering left to do, but we plan to start testing next week and will keep you posted on the outcome. If everything goes well for our project, we'd love to contribute back.

**Comment by lafiosca** [comment]
Very interesting, thank you for the followup!

**Comment by lafiosca** [comment]
Closing this PR for now

**Comment by vchaitanya88** [comment]
is this fixed?
can you tell me how to fix it?

**Pull request closed without merging**
