### PR TITLE
add snapbackAnimator prop to DraxView; potentially closes #28

### LINKED ISSUE #28: Feature Request: Allow specifying custom Animated function for moving/snapping dropped items
It would be great to be able to specify the animation for a dropped item. Right now it is this timing function: 

https://github.com/nuclearpasta/react-native-drax/blob/master/src/hooks/useDraxRegistry.ts#L493

I confirmed that I could manually change that to the spring function and it worked as expected. I could probably take a look at doing this. It should be a fairly straightforward option to configure.

### PR DESCRIPTION
**Pull request by lafiosca**
Created this PR in response to #28 from @special-character

### CODE REVIEW

**Comment by special-character** [comment]
@lafiosca Thanks for taking a look at this, it looks great.

**Comment by lafiosca** [comment]
I'm going to give it some tests myself this Thursday evening, and if all looks good I will merge and make a point release.

**Comment by lafiosca** [comment]
Ran long on the other issues tonight, will have to postpone release likely until this weekend.

**Comment by lafiosca** [comment]
Tests look good, rebased to latest `prerelease` changes. :)

**Pull request merged**
